// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApi.Entities
{
    public partial class CELRATE
    {
        [Key]
        [StringLength(3)]
        public string PTYPE { get; set; }
        [StringLength(150)]
        public string PTYDSC { get; set; }
        [Column(TypeName = "decimal(19, 0)")]
        public decimal? PLNGRP { get; set; }
        [StringLength(150)]
        public string PGRDSC { get; set; }
        [Column(TypeName = "decimal(19, 0)")]
        public decimal? PRRCEL { get; set; }
        [Column(TypeName = "decimal(16, 11)")]
        public decimal? PRRCELRATE { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CREATE_DATE { get; set; }
    }
}