// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApi.Entities
{
    public partial class LateCharge
    {
        [Key]
        public Guid LID { get; set; }
        [StringLength(50)]
        public string ApplicationNo { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? FirstLateCharge { get; set; }
        [StringLength(10)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(10)]
        public string UpdateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? MrrRate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? MrrEffectiveRateDate { get; set; }
    }
}