// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApi.Entities
{
    public partial class LNPAR2
    {
        [Key]
        [StringLength(3)]
        public string PTYPE { get; set; }
        [Required]
        [StringLength(150)]
        public string PTYDSC { get; set; }
        [Column(TypeName = "decimal(3, 0)")]
        public decimal PLNGRP { get; set; }
        [Required]
        [StringLength(20)]
        public string PGRDSC { get; set; }
        [Column(TypeName = "decimal(3, 0)")]
        public decimal? LATCHGCOD { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CREATE_DATE { get; set; }
    }
}