// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApi.Entities
{
    public partial class SSRATE
    {
        [StringLength(5)]
        public string JRSTAT { get; set; }
        [Key]
        [Column(TypeName = "decimal(3, 0)")]
        public decimal JRRATN { get; set; }
        [StringLength(4)]
        public string JRRCUR { get; set; }
        [Column(TypeName = "decimal(2, 0)")]
        public decimal? JRBANK { get; set; }
        [Column(TypeName = "decimal(3, 0)")]
        public decimal? JRBRAN { get; set; }
        [Column(TypeName = "decimal(18, 9)")]
        public decimal? JRCRAT { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? JRDATE { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? JRLFMD { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? JRRDA6 { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? JRRDA7 { get; set; }
        [Column(TypeName = "decimal(18, 0)")]
        public decimal? JRRFRQ { get; set; }
        [StringLength(5)]
        public string JRRFRC { get; set; }
        [StringLength(10)]
        public string JRRNAM { get; set; }
        [StringLength(150)]
        public string JRDESC { get; set; }
        [Column(TypeName = "decimal(3, 0)")]
        public decimal? JRREFR { get; set; }
        [Column(TypeName = "decimal(11, 9)")]
        public decimal? JRREFI { get; set; }
        [Column(TypeName = "decimal(6, 0)")]
        public decimal? JRTIME { get; set; }
        [StringLength(50)]
        public string JRWSID { get; set; }
        [StringLength(50)]
        public string JRUSID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CREATE_DATE { get; set; }
        [Column(TypeName = "decimal(11, 9)")]
        public decimal? JRCRAT_FUTURE { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? JRDATE_FUTURE { get; set; }
    }
}