// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace WebApi.Entities.Models
{
    public partial class ConfigGroupQuestion
    {
        [Key]
        public Guid IdConfigGroupQuestion { get; set; }
        public Guid IdGroup { get; set; }
        public Guid IdQuestion { get; set; }
        [Required]
        [StringLength(10)]
        public string CreateDate { get; set; }
        [Required]
        [StringLength(10)]
        public string CreateBy { get; set; }
        [Required]
        public bool? IsActive { get; set; }
    }
}