// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using WebApi.Entities;

#nullable disable

namespace WebApi.Entities.DdContextTcrb
{
    public partial class LatechargeContext : DbContext
    {
        public LatechargeContext()
        {
        }

        public LatechargeContext(DbContextOptions<LatechargeContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CELRATE> CELRATE { get; set; }
        public virtual DbSet<LNPAR2> LNPAR2 { get; set; }
        public virtual DbSet<LateCharge> LateCharge { get; set; }
        public virtual DbSet<LateCharge_Log> LateCharge_Log { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
        public virtual DbSet<SSRATE> SSRATE { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Thai_CI_AS");

            modelBuilder.Entity<CELRATE>(entity =>
            {
                entity.Property(e => e.PTYPE).IsUnicode(false);

                entity.Property(e => e.PGRDSC).IsUnicode(false);

                entity.Property(e => e.PTYDSC).IsUnicode(false);
            });

            modelBuilder.Entity<LNPAR2>(entity =>
            {
                entity.Property(e => e.PTYPE).IsUnicode(false);

                entity.Property(e => e.PGRDSC).IsUnicode(false);

                entity.Property(e => e.PTYDSC).IsUnicode(false);
            });

            modelBuilder.Entity<LateCharge>(entity =>
            {
                entity.Property(e => e.LID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.ApplicationNo).IsUnicode(false);

                entity.Property(e => e.CreateBy).IsUnicode(false);

                entity.Property(e => e.UpdateBy).IsUnicode(false);
            });

            modelBuilder.Entity<LateCharge_Log>(entity =>
            {
                entity.Property(e => e.LogID).HasDefaultValueSql("(newid())");

                entity.Property(e => e.ApplicationNo).IsUnicode(false);

                entity.Property(e => e.CreateBy).IsUnicode(false);

                entity.Property(e => e.EventType).IsUnicode(false);

                entity.Property(e => e.UpdateBy).IsUnicode(false);
            });

            modelBuilder.Entity<Parameter>(entity =>
            {
                entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

                entity.Property(e => e.CreateBy).IsUnicode(false);

                entity.Property(e => e.Name).IsUnicode(false);

                entity.Property(e => e.Value).IsUnicode(false);
            });

            modelBuilder.Entity<SSRATE>(entity =>
            {
                entity.Property(e => e.JRDESC).IsUnicode(false);

                entity.Property(e => e.JRRCUR).IsUnicode(false);

                entity.Property(e => e.JRRFRC).IsUnicode(false);

                entity.Property(e => e.JRRNAM).IsUnicode(false);

                entity.Property(e => e.JRSTAT).IsUnicode(false);

                entity.Property(e => e.JRUSID).IsUnicode(false);

                entity.Property(e => e.JRWSID).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}